### PR TITLE
Updated the README document so it's more clear

### PR DESCRIPTION
**Pull request by Mengting233**
I tried the previous instruction, some steps are a little bit confuse and unclear. So I updated the README file to make it more clear.

### CODE REVIEW

**Comment by afrose-97** [comment]
Thank you Xie! Appreciated.

**Comment by Mengting233** [comment]
@afrose-97 Thank YOU so much! This custom control is brilliant and works like charm, once I figured out how to push it correctly to my environment 👍😁.

**Comment by afrose-97** [comment]
Glad to hear it!

**Comment by afrose-97** [comment]
README file Updated

**Pull request closed without merging**
